language: perl

os:
  - linux
  # - osx

# services:
  # - docker

perl:
  # - "5.26-extras"
  - "5.24-extras"
  - "5.22-extras"
  - "5.20-extras"
  - "5.18-extras"

install:
  - cpanm --skip-satisfied -q -n Gedcom Moo~2.002004 Genealogy::Gedcom::Date Date::Parse Getopt::Std Geo::Coder::OSM Term::ANSIColor Lingua::EN::NameParse Lingua::EN::NameCase Lingua::EN::Numbers::Ordinate Tie::Static DateTime::Format::Natural HTML::Entities B::Lint HTTP::Cache::Transparent Image::Info URI::Find::Schemeless URI LWP::Simple LWP::UserAgent::Throttled HTML::GoogleMaps::V3 Sort::Key::DateTime String::ProgressBar Text::Names::GB IPC::System::Simple autodie Memoize Lingua::EN::ABC warnings::unused File::Copy Data::Fetch Geo::Coder::GooglePlaces Geo::Coder::List Config::Auto Lingua::EN::Inflect Geo::Coder::CA DBD::SQLite Locale::Object::Country FCGI Log::Log4perl CGI::Carp CGI::Info CGI::Lingua FCGI::Buffer File::HomeDir Log::WarnDie Template::Plugin::EnvHash CHI HTML::SocialMedia Statistics::LineFit File::pfopen Statistics::Lite Geo::Coder::XYZ Geo::StreetAddress::US Locale::US Log::Any::Adapter::Log4perl Text::CSV::Slurp

script:
  - perl -c -MO=Lint ./ged2site
  - perl -c -Mwarnings::unused ./ged2site
  - cd dynamic-site/cgi-bin && perl -c -MO=Lint ./page.fcgi '' && perl -c -Mwarnings::unused ./page.fcgi ''
